### ISSUE TITLE
Why no delete method

### ISSUE THREAD

**Issue by purplejacket** [bryanch/quick-sorted-list#1]
Do I misunderstand the concept of this data structure?  Why wouldn't there be a method to delete the entry at a given position?  the *cut* method seems heavy handed.

**Comment by bryanch** [comment]
The cut method is to satisfy a requirement from one of my other projects, there would be a remove method to remove a single element at a given position, just in backlog.

**Comment by bryanch** [comment]
Added a removeByIndex method in 1.0.5.
